# spring配置
spring: 
  redis:
    host: 218.78.103.93
    port: 6379
    password: mqtts
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
          # 主库数据源
          master:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://218.78.103.93:3306/mqtts?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
            username: mqtts
            password: 3jZYkeD5NR8WzKZ6
          # 从库数据源
          # slave:
            # username: 
            # password: 
            # url: 
            # driver-class-name: 
      # seata: true    # 开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭

# seata配置
seata:
  # 默认关闭，如需启用spring.datasource.dynami.seata需要同时开启
  enabled: false
  # Seata 应用编号，默认为 ${spring.application.name}
  application-id: ${spring.application.name}
  # Seata 事务组编号，用于 TC 集群名
  tx-service-group: ${spring.application.name}-group
  # 关闭自动代理
  enable-auto-data-source-proxy: false
  # 服务配置项
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      ruoyi-system-group: default
  config:
    type: nacos
    nacos:
      serverAddr: 218.78.103.93:8848
      group: SEATA_GROUP
      namespace: d52c413e-9b5c-4ee7-b4c2-7950ebe0a0d6
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 218.78.103.93:8848
      namespace: d52c413e-9b5c-4ee7-b4c2-7950ebe0a0d6

# mybatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: net.mqtts.link
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mapper/**/*.xml

# swagger配置
swagger:
  title: Link模块接口文档
  license: Powered By mqtts
  licenseUrl: https://doc.mqtts.net

#smqtt官方配置文件V1.0.9
smqtt:
  logLevel: DEBUG # 系统日志
  tcp: # tcp配置
    port: 11883 # mqtt端口号
    username: mqtts # mqtt连接默认用户名  生产环境建议spi去注入PasswordAuthentication接口
    password: mqtts  # mqtt连接默认密码 生产环境建议spi去注入PasswordAuthentication接口
    wiretap: true  # 二进制日志 前提是 smqtt.logLevel = DEBUG
    bossThreadSize: 4  # boss线程 默认=cpu核心数
    workThreadSize: 8  # work线程 默认=cpu核心数*2
    businessThreadSize: 16 # 业务线程数 默认=cpu核心数*10
    businessQueueSize: 100000 #业务队列 默认=100000
    lowWaterMark: 4000000 # 不建议配置 默认 32768
    highWaterMark: 80000000 # 不建议配置 默认 65536
    options: # netty option设置
      SO_BACKLOG: 200
    childOptions:  #netty child option设置
      SO_REUSEADDR: true
    ssl: # ssl配置
      enable: false # 开关
      key: classpath:ssl/server.key # 指定ssl文件 默认系统生成
      crt: classpath:ssl/server.crt # 指定ssl文件 默认系统生成
  http: # http相关配置 端口固定60000
    enable: true # 开关
    accessLog: true # http访问日志
    ssl: # ssl配置
      enable: false
  ws: # websocket配置
    enable: true # 开关
    port: 18999 # 端口
    path: /mqtt # ws 的访问path mqtt.js请设置此选项
  cluster: # 集群配置
    enable: false # 集群开关
    url: 127.0.0.1:7771,127.0.0.1:7772 # 启动节点
    port: 7771  # 端口
    node: node-1 # 集群节点名称 唯一
    namespace: smqtt
    external:
      host: localhost # 用于映射容器ip 请不要随意设置，如果不需要请移除此选项
      port: 7777 # 用于映射容器端口 请不要随意设置，如果不需要请移除此选项
  rules: # 规则引擎相关配置
    - ruleName: 过滤
      chain: # 规则链
        - ruleType: ROCKET_MQ  # ROCKET_MQ过滤器
          script:  '{"topic":"${topic}","msg":"${msg.test}","qos":${qos}}'
        # - ruleType: HTTP
        #   script:  '{"topic":"${topic}","msg":"${msg.test}","qos":${qos}}'
  sources: # 配置数据源sources
    - source: ROCKET_MQ # rocketmq配置
      sourceName: rocket_mq
      sourceAttributes:
        topic: mqtts
        tags: mqtts
        namesrvAddr: 127.0.0.1:9876
        instanceName: wt9zfxnoukxsrngp-0721852
        producerGroup: mqtts
    # - source: HTTP
    #   sourceName: http
    #   sourceAttributes:
    #     url: http://127.0.0.1:60027/publishTopic/reqSysTimeEvtPublishData
    #     port: 80
    #     headers:
    #       Authorization: token value