# spring配置
spring: 
  redis:
    host: 218.78.103.93
    port: 6379
    password: mqtts
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://218.78.103.93:3306/mqtts?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: mqtts
    password: 3jZYkeD5NR8WzKZ6

# mybatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: net.mqtts.job.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mapper/**/*.xml

# swagger配置
swagger:
  title: 定时任务接口文档
  license: Powered By mqtts
  licenseUrl: https://doc.mqtts.net
