spring: 
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: thinglinks
    timeout: 30000
    jedis:
      pool:
      # 连接池中的最大空闲连接
        max-idle: 20
      # 连接池中的最小空闲连接
        min-idle: 0
      # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  datasource: 
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    url: jdbc:TAOS-RS://124.223.113.139:6041/thinglinks?timezone=UTC-8&charset=UTF-8&locale=en_US.UTF-8
    username: root
    password: taosdata
    druid: 
      initial-size: 5
      min-idle: 5
      max-active: 5
      max-wait: 30000
      validation-query: select server_status();
  aop: 
    auto: true
    proxy-target-class: true
mybatis: 
  mapper-locations: classpath:mapper/*.xml

# rocketmq地址
rocketmq: 
  name-server: 127.0.0.1:9876
# 默认的消息组
  producer: 
    group: thinglinks

    
logging:  
  level: 
    com: 
      taosdata: 
        jdbc: 
          springbootdemo: 
            dao: debug